//styles/registro.styles.ts
import { StyleSheet } from 'react-native';
import { COLORS } from '../constants/theme';

export const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  scrollContainer: {
    paddingHorizontal: 20,
    paddingTop: 40,
    paddingBottom: 100,
    alignItems: 'center',
  },
  fixedButtonContainer: {
    alignItems: 'center',
    bottom: 50,
    left: 0,
    right: 0,
    paddingHorizontal: 20,
    backgroundColor: COLORS.background,
  },
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
    paddingHorizontal: 20,
    paddingTop: 40,
    alignItems: 'center',
  },
  screenTitle: {
    fontSize: 28,
    fontWeight: '700',
    color: COLORS.textPrimary,
    marginTop: 80,
    marginBottom: 100,
    textAlign: 'center',
  },
  placaInput: {
    width: '85%',
    height: 60,
    backgroundColor: COLORS.surface,
    borderWidth: 2,
    borderColor: COLORS.border,
    borderRadius: 16,
    paddingHorizontal: 20,
    fontSize: 28,
    fontWeight: 'bold',
    letterSpacing: 1.5,
    color: COLORS.textPrimary,
    textAlign: 'center',
    textTransform: 'uppercase',
    marginBottom: 80,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 3,
  },
  subtitle: {
    fontSize: 16,
    color: COLORS.textSecondary,
    marginBottom: 25,
    textAlign: 'center',
    fontWeight: '500',
  },
  typesContainer: {
    minHeight: 200,
    paddingBottom: 10,
  },
  typeCard: {
    width: 140,
    height: 160,
    backgroundColor: COLORS.surface,
    borderRadius: 16,
    marginHorizontal: 10,
    padding: 16,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: COLORS.border,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 3,
  },
  selectedCard: {
    borderColor: COLORS.primary,
    backgroundColor: COLORS.primary + '08',
    shadowColor: COLORS.primary,
    shadowOpacity: 0.15,
  },
  typeText: {
    marginTop: 12,
    fontSize: 14,
    color: COLORS.textSecondary,
    textAlign: 'center',
    fontWeight: '500',
  },
  selectedText: {
    color: COLORS.primary,
    fontWeight: '600',
  },
  buttonContainer: {
    width: '90%',
    alignItems: 'center',
  },
  confirmButton: {
    width: '85%',
    backgroundColor: COLORS.primary,
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: 'center',
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  buttonText: {
    color: COLORS.surface,
    fontSize: 16,
    fontWeight: '600',
  },
  cancelButton: {
    marginTop: 12,
    marginBottom: 25,
    padding: 12,
  },
  cancelText: {
    color: COLORS.textSecondary,
    fontSize: 14,
    fontWeight: '500',
    textDecorationLine: 'underline',
  },
  registroContainer: {
    flexGrow: 1,
    padding: 20,
    backgroundColor: COLORS.background,
    justifyContent: 'center',
  },
  centeredCard: {
    width: '90%',
    height: 200,
    backgroundColor: COLORS.surface,
    borderRadius: 20,
    marginVertical: 15,
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.border,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
  },
  cardIcon: {
    marginBottom: 15,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: COLORS.textPrimary,
    textAlign: 'center',
  },
  vehicleImage: {
    width: 80,
    height: 60,
    marginBottom: 8
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.background,
  },
  disabledButton: {
    backgroundColor: COLORS.textMuted + '60',
  },
  searchButton: {
    width: '70%',
    backgroundColor: COLORS.info,
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: 'center',
    marginBottom: 30,
    shadowColor: COLORS.info,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 2,
  },
  vehiculosContainer: {
    width: '100%',
    maxHeight: 300,
  },
  vehiculoCard: {
    backgroundColor: COLORS.surface,
    borderRadius: 12,
    padding: 15,
    marginVertical: 5,
    marginHorizontal: 10,
    borderWidth: 1,
    borderColor: COLORS.border,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  selectedVehiculoCard: {
    borderWidth: 2,
    borderColor: COLORS.primary,
    backgroundColor: COLORS.primary + '08',
  },
  vehiculoHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  vehiculoPlaca: {
    fontSize: 18,
    fontWeight: 'bold',
    color: COLORS.textPrimary,
    letterSpacing: 1,
  },
  vehiculoTipo: {
    fontSize: 14,
    color: COLORS.textSecondary,
    fontWeight: '500',
  },
  vehiculoInfo: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  vehiculoEspacio: {
    fontSize: 14,
    color: COLORS.primary,
    fontWeight: '500',
  },
  vehiculoTiempo: {
    fontSize: 14,
    color: COLORS.warning,
    fontWeight: '500',
  },
  emptyContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 40,
  },
  emptyText: {
    fontSize: 16,
    color: COLORS.textSecondary,
    textAlign: 'center',
    lineHeight: 24,
  },
  cardImageContainer: {
    marginBottom: 15,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardImage: {
    width: 80,
    height: 60,
  },
});